version: '3'

services:

  pg_master:
    build: ./docker-build/master
    container_name: pg_master
    restart: always
    volumes:
      - m-data:/var/lib/postgresql/data:z
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${MASTER_DB_PASSWORD}
      - POSTGRES_DB=master_db

      - POSTGRES_MASTER=pg_slave_1
      - POSTGRES_REP_USER=replicator
      - POSTGRES_REP_PASSWORD=${REPLICATOR_PASSWORD}
    networks:
      - databases-network

  pg_slave_1:
    build: ./docker-build/slave
    container_name: pg_slave_1
    restart: always
    volumes:
      - slave1-data:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SLAVE_1_DB_PASSWORD}
      - POSTGRES_DB=slave_1_db

      - POSTGRES_MASTER=pg_master
      - POSTGRES_REP_USER=replicator
      - POSTGRES_REP_PASSWORD=${REPLICATOR_PASSWORD}

      - PG_STANDBY=true
    networks:
      - databases-network

volumes:
  m-data:
  slave1-data:

networks:
  databases-network:
    external:
      name: databases-network
